ChatApp/ChatApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_chat.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ChatApp/my_chat/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)
        verbose_name = 'Сообщение чата'
        verbose_name_plural = 'Сообщения чатов'


class GroupChat(models.Model):
    members = models.ManyToManyField(User, through='GroupChatUser', related_name='members')
    chat_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='chat_author')
    group_chat_title = models.CharField(max_length=64)
    photo_chat = models.ImageField(upload_to='group_chat_avatars', default='default_avatar/default.jpg')

    def __str__(self):
        return self.group_chat_title

    class Meta:
        verbose_name = 'Групповой чат'
        verbose_name_plural = 'Групповые чаты'

    def get_absolute_url(self):
        return reverse('group_chat', args=[str(self.id)])


class GroupChatUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group_chat = models.ForeignKey(GroupChat, on_delete=models.CASCADE)


class GroupMessage(models.Model):
    group_chat = models.ForeignKey(GroupChat, related_name='chat', on_delete=models.CASCADE)
    group_sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='group_sender', null=True, blank=True)
    group_message = models.CharField(max_length=1200)
    group_timestamp = models.DateTimeField(auto_now_add=True)
    group_is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.group_message

    class Meta:
        ordering = ('group_timestamp',)
        verbose_name = 'Сообшение группового чата'
        verbose_name_plural = 'Сообщения групповых чатов'


class ProfilePhoto(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='avatars', default='default_avatar/default.jpg')

    def __str__(self):
        return User.objects.get(id=self.user_id).username

    class Meta:
        verbose_name = 'Фото автара'
        verbose_name_plural = 'Фотографии для аватаров'

ChatApp/templates/chat/chat.html
{% extends 'chat/index.html' %}
{% block body %}
<style>
    .wrapper1 {
        width: 150px;
        height: 200px;
        border: 5px solid #515151;
        display: flex;
        justify-content: left;
        margin-top: 10px;
    }
    .avatar1 img {
        object-fit: cover;
        width: 100%;
        height: 100%;
     }
    .right {
        float:right;
        margin: 7px 7px 7px 0; /* Отступы вокруг картинки */
        justify-content: center;
    }
    .parent {
      display: flex;
      justify-content: left;
      margin-top: 10px;
    }
    .child {
      border: 2px #e0cfb1;
      margin: 20px;
    }
    h2 {
      font-family: 'Playfair Display SC', serif;
      font-weight: 500;
      letter-spacing: 1px;
      font-size: 48px;
      color: #222222;
      text-align: center;
    }
    .textright {
      margin: 0 10px 20px 50px;;
      font-size: 32px;
    }
</style>
<nav class="blue lighten-3">
    <div class="nav-wrapper container">
      <a href="{% url 'chats' %}" class="brand-logo">Пользователи</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'group_chats' %}">Групповые чаты</a></li>
          <li><a href="{% url 'profile_view' %}">{{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>
</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
        <div class="card">
            <div class="collection">
                {% if users %}
                    {% for user in users %}
                    <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                        <div class="wrapper1 avatar1">
                            <img src="{{ user.profilephoto.photo.url }}" alt="My image">
                            <div class="textright">
                                <p>{{ user.username }}</p>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                {% else %}
                    <div>
                        <h2>Пока некому написать :(</h2>
                    </div>
                {% endif %}
            </div>
        </div>
        </div>
        <div class="col s9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Наберите своё сообщение здесь...">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating blue lighten-2 waves-effect waves-light"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load static %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                let message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
        })
    </script>
{% endblock %}

ChatApp/templates/chat/default.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
 <style>
    h2 {
      font-family: 'Playfair Display SC', serif;
      font-weight: 500;
      letter-spacing: 1px;
      font-size: 48px;
      color: #222222;
      text-align: center;
    }
    .wrapper {
        width: 500px;
        height: 700px;
        border: 5px solid #515151;
    }
    .mybtn{
      color: black;
      background-color: #87CEFA;
      padding-top: 10px;
      padding-bottom: 10px;
      display: flex;
      align-items: center;
      justify-content: center;
      border-radius: 10px; /* Уголки */
    }

    .container {
      width: 30%;
    }
</style>
</head>
<body>
<nav class="blue lighten-3">
    <div class="nav-wrapper container">
      <a href="{% url 'chats' %}" class="brand-logo">Пользователи</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'group_chats' %}">Групповые чаты</a></li>
          <li><a href="{% url 'profile_view' %}">{{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>
</nav>
{% block content %}
  {{ flatpage.content }}
{% endblock content %}
</body>
</html>

ChatApp/templates/chat/group_chat.html
{% extends 'chat/index.html' %}
{% block body %}
{% load static %}
<link href="{% static 'css/group_chat.css' %}" rel="stylesheet" />
<nav class="blue lighten-3">
    <div class="nav-wrapper container">
      <a href="{% url 'chats' %}" class="brand-logo">Пользователи</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'group_chats' %}">Групповые чаты</a></li>
          <li><a href="{% url 'profile_view' %}">{{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>
</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
        <div class="card">
            <div class="collection">
            <a href="{% url 'group_chat_create' %}" class="mybtn">Создать чат</a>
                {% if group_chats %}
                    {% for item in group_chats %}
                        <div class="wrapper1 avatar1">
                            <img src="{{ item.photo_chat.url }}" alt="My image">
                            <div>
                                {% if request.user.id == item.chat_author_id %}
                                    <a href="{% url 'group_chat_users' item.id %}" class="mybtns">Добавление/удаление пользователя</a>
                                    <a href="{% url 'group_chat_edit' item.id %}" class="mybtns">Редактировать</a>
                                    <a href="{% url 'group_chat_delete' item.id %}" class="mybtns">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                        <a href="{% url 'group_chat' item.id %}" id="item{{ item.id }}" class="collection-item row">
                        <div class="textright">
                            <p>{{ item.group_chat_title }}</p>
                        </div>
                        </a>
                    {% endfor %}
                {% else %}
                    <div>
                        <h2>Вы не создали чат, или не приглашены ни в один из созданных</h2>
                    </div>
                {% endif %}
            </div>
        </div>
        </div>
        <div class="col s9">
            <div>
                <strong>Владелец чата: {{ author }} Пользователи: </strong>
                {% for user in users_in_chat %}
                    <strong>|{{ user.username }}|</strong>
                {% endfor %}
            </div>
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Наберите своё сообщение здесь...">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating blue lighten-2 waves-effect waves-light"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load static %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        function groupSend(group_chat, group_sender, group_message) {
            $.post('/api/group_messages/', '{"group_chat": "'+ group_chat +'","group_sender": "'+ group_sender +'","group_message": "'+ group_message +'" }', function (data) {
                console.log(data);
                let box = chat_box.replace('{sender}', "Вы");
                box = box.replace('{message}', group_message);
                $('#board').append(box);
                scrolltoend();
            })
        }
        // For receiving and sending url REST
        chat_id = "{{ chat_id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                let message = $('#id_message');
                groupSend('{{ chat_id }}', '{{ request.user.username }}', message.val());
                message.val('');
            })
        })
    </script>
{% endblock %}

ChatApp/templates/chat/group_chat_create.html
{% extends 'chat/default.html' %}

{% block content %}
{% load static %}
<link href="{% static 'css/group_chat.css' %}" rel="stylesheet" />
<div class="wrapper container">
  <h2>Создайте чат здесь!</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="mybtn" value="Добавить чат">
    </form>
</div>
{% endblock content %}

ChatApp/templates/chat/group_chat_delete.html
{% extends 'chat/default.html' %}

{% block content %}
{% load static %}
<link href="{% static 'css/group_chat.css' %}" rel="stylesheet" />
<div class="wrapper container">
    <h2>Удаление чата</h2>
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        <h2>Удаляем чат "{{ object.group_chat_title }}"?</h2>
        <input type="submit" class="mybtn" value="Удалить" />
    </form>
</div>
{% endblock content %}

ChatApp/templates/chat/group_chat_edit.html
{% extends 'chat/default.html' %}

{% block content %}
{% load static %}
<link href="{% static 'css/group_chat.css' %}" rel="stylesheet" />
<div class="wrapper container">
  <h2>Измените чат здесь!</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="mybtn" value="Сохранить изменения">
    </form>
</div>
{% endblock content %}

ChatApp/templates/chat/group_chat_users.html
{% extends 'chat/default.html' %}

{% block content %}
{% load static %}
<link href="{% static 'css/group_chat.css' %}" rel="stylesheet" />

<div>
    <h2>Удаление пользователей из чата {{ chat.group_chat_title }}:</h2>
    {% for user in users_in_chat %}
    {% csrf_token %}
    <form class="grusers" method="post">
        <button class="mybtn" type="submit" name="delete_user" value="{{ user.id }}">{{ user }}</button>
    </form>
    {% endfor %}
</div>
<hr>
<div>
    <h2>Добавление пользователей в чат {{ chat.group_chat_title }}</h2>
    {% for user in users_not_in_chat %}
    {% csrf_token %}
    <form class="grusers" method="post">
        <button class="mybtn"  type="submit" name="add_user" value="{{ user.id }}">{{ user }}</button>
    </form>
    {% endfor %}
</div>

{% endblock content %}

ChatApp/templates/chat/group_messages.html
{% extends 'chat/group_chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.group_sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">Вы</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.group_sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
let chat_box = '<div class="card-panel right" style="width: 75%; position: relative">' +
        '<div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{sender}</div>' +
        '{message}' +
        '</div>';
function groupReceive() {
    $.get('/api/group_messages/'+ chat_id, function (data) {
        console.log(data);
        if (data.length !== 0)
        {
            for(let i=0;i<data.length;i++) {
                console.log(data[i]);
                let box = chat_box.replace('{sender}', data[i].sender);
                box = box.replace('{message}', data[i].message);
                box = box.replace('right', 'left blue lighten-5');
                $('#board').append(box);
                scrolltoend();
            }
        }
    })
}
$(function () {
    $('#chat{{ item.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(groupReceive,1000)
})
</script>
{% endblock %}

ChatApp/templates/chat/index.html
{% load static %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>

    <body>
    {% block body %}
        <div class="section blue lighten-3">
            <div class="container white-text center-align text">
            <h2>Учебный проект для SkillFactory от Владислава</h2>
            <p>Приложение - чат</p>
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3>
                    Login
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}">Register</a>
                            </div>
                            <div class="col s4">
                            <div class="right">
                                <button class="btn blue waves-effect waves-light pull-s12">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>

  </html>

ChatApp/templates/chat/messages.html
{% extends 'chat/chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">Вы</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

ChatApp/templates/chat/profile.html
{% extends 'chat/default.html' %}

{% block content %}
{% load static %}
<link href="{% static 'css/group_chat.css' %}" rel="stylesheet" />
<div class="bd">
    <div class="parent">
        <div class="wrapper avatar"><img src="{{ request.user.profilephoto.photo.url }}" alt="My image"></div>
        <div class="child">
            <h2>Профиль пользователя {{ request.user.username }}</h2>
            <form id="register-form" class="form-group" method="POST">
            {% csrf_token %}
                <div class="row">
                    <div class="input-field col s12">
                        {{ form_nick.username }}
                        <label for="id_username" data-error="Username already taken">Введите новый никнейм</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                    <div class="right">
                        <button class="btn" name="change" value="nickname">Изменить никнейм</button>
                    </div>
                    </div>
                </div>
        </form>
        </div>
    </div>
    <div class="parent">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
           {{ form_photo.as_p }}
          <button type="submit" class="btn" name="change" value="photo">Загрузить фото</button>
        </form>
    </div>
</div>
{% endblock %}

ChatApp/templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3>
    Регистрация
    </h3>
    <form id="register-form" class="form-group" method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    {{ form.username }}
                    <label for="id_username" data-error="Username already taken">Никнейм</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password1 }}
                    <label for="id_password">Пароль</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password2 }}
                    <label for="id_password2">Повторите пароль</label>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                <div class="right">
                    <button class="btn blue waves-effect waves-light pull-s12">Регистрация</button>
                </div>
                </div>
            </div>
    </form>
{% endblock %}